plugins {
    id 'com.github.spotbugs' version '6.0.27' apply false
    id 'com.github.hierynomus.license' version '0.16.1' apply false
}

allprojects {
    apply plugin: 'java-library'
    apply plugin: 'eclipse'
    apply plugin: 'checkstyle'
    apply plugin: 'com.github.spotbugs'
    apply plugin: 'jacoco'
    apply plugin: 'idea'
    apply plugin: 'com.github.hierynomus.license'
    apply plugin: 'project-report'

    repositories {
        mavenCentral()
        maven {
            url = 'https://repo.spring.io/milestone'
        }
        maven {
            url = 'https://repo.spring.io/snapshot'
        }
    }

    eclipse {
        classpath {
            downloadSources = true
        }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
    }

    license {
        ext.year = Calendar.getInstance().get(Calendar.YEAR)
        header = rootProject.file("${rootDir}/config/LICENSE_TEMPLATE")
        ignoreFailures = false
        skipExistingHeaders = true
        strictCheck = true
        useDefaultMappings = false
        mapping('java', "SLASHSTAR_STYLE")
    }

    tasks.named('compileJava') {
        dependsOn 'licenseTest'
    }
    tasks.named('compileTestJava') {
        dependsOn 'licenseTest'
    }

    configurations.configureEach {
        exclude group: 'commons-logging', module: 'commons-logging'
    }

    ext {
        springVersion = '4.0.2.RELEASE'
        springMongoVersion = '1.4.0.M1'
        springAmqpVersion = '1.3.0.RC1'
        springRetryVersion = '1.0.3.RELEASE'
        jaxRsVersion = '2.0'
        jacksonVersion = '1.9.13'
        jerseyVersion = '2.7'
        mybatisVersion = '3.2.5'
        mybatisSpringVersion = '1.2.2'
        beanValidationVersion = '1.1.0.Final'
        hibernateValidatorVersion = '5.1.0.Final'
        elVersion = '2.2.4'
        commonsFileuploadVersion = '1.3.1'
        commonsValidatorVersion = '1.4.0'
        commonsDbcpVersion = '1.4'
        commonsIoVersion = '2.0.1'
        commonsCollectionsVersion = '3.2.1'
        commonsLangVersion = '2.6'
        commonsCodecVersion = '1.5'
        slf4jVersion = '1.7.6'
        logbackVersion = '1.1.1'
        guavaVersion = '16.0.1'
        openCsvVersion = '2.3'

        junitVersion = '4.11'
        mockitoVersion = '1.9.5'
        h2Version = '1.3.173'

        servletApiVersion = '3.0.1'
        cglibVersion = '3.1'
        asmVersion = '3.3.1'
        aspectjVersion = '1.7.3'
        jspApiVersion = '2.2'
        jstlVersion = '1.2'

        checkstyleVersion = '10.21.4'
    }

    dependencies {
        implementation "org.slf4j:slf4j-api:${slf4jVersion}"
        implementation "ch.qos.logback:logback-classic:${logbackVersion}"
        implementation "org.slf4j:jcl-over-slf4j:${slf4jVersion}"
        implementation "com.google.guava:guava:${guavaVersion}"
        implementation "commons-lang:commons-lang:${commonsLangVersion}"
        testImplementation "junit:junit:${junitVersion}"
        testImplementation "org.mockito:mockito-core:${mockitoVersion}"
        runtimeOnly "cglib:cglib-nodep:${cglibVersion}"
        runtimeOnly "asm:asm:${asmVersion}"
        runtimeOnly "org.aspectj:aspectjweaver:${aspectjVersion}"
        implementation "javax.annotation:javax.annotation-api:1.3.2"
        runtimeOnly "javax.xml.bind:jaxb-api:2.3.1"
        runtimeOnly "org.glassfish.jaxb:jaxb-runtime:2.3.9"
        compileOnly "javax.servlet:javax.servlet-api:${servletApiVersion}"
        testImplementation "javax.servlet:javax.servlet-api:${servletApiVersion}"
        testImplementation "javax.servlet.jsp:jsp-api:${jspApiVersion}"
        testImplementation "javax.servlet:jstl:${jstlVersion}"
    }

    test {
        testLogging {
            events "failed"
            exceptionFormat "full"
            debug {
                events "started", "skipped", "failed"
                exceptionFormat "full"
            }
        }
        exclude '**/*$*'
    }

    checkstyle {
        configFile = file("${rootDir}/config/checkstyle/ctc-checks.xml")
        ignoreFailures = true
        toolVersion = checkstyleVersion
    }

    spotbugs {
        ignoreFailures = true
    }

    jacoco {
        toolVersion = '0.8.12'
    }

    jacocoTestReport {
        reports {
            xml.required.set(false)
            csv.required.set(false)
            html.outputLocation.set(layout.buildDirectory.dir("jacocoHtml"))
        }
    }

    task resourceCopy(type: Copy) {
        dependsOn processResources
        from processResources.destinationDir
        into compileTestJava.destinationDirectory
        include '**/*.xml'
        include '*.xml'
        include '*.properties'
    }

    tasks.named('test') {
        dependsOn 'resourceCopy'
    }
}

configure(subprojects) { subproject ->
    apply plugin: 'maven-publish'
    apply plugin: 'signing'

    group = 'jp.co.ctc-g.jfw'
    defaultTasks 'clean', 'packages'

    jar {
        doFirst {
            manifest.attributes["Created-By"] = "${System.getProperty("java.version")}"
            manifest.attributes["Implementation-Vendor"] = 'ITOCHU Techno-Solutions Corporation.'
            manifest.attributes["Implementation-Title"] = subproject.name
            manifest.attributes["Implementation-Version"] = subproject.version
        }
    }

    javadoc {
        doFirst {
            description = "Generates project-level javadoc for use in -javadoc jar"
            options.memberLevel = org.gradle.external.javadoc.JavadocMemberLevel.PROTECTED
            options.author = true
            options.overview = "${rootDir}/config/javadoc/html/overview.html"
            options.charSet = 'UTF-8'
            options.docTitle = "${subproject.name} ${subproject.version}"
            options.windowTitle = "${subproject.name} ${subproject.version}"
            options.header = "<h1>${subproject.name}</h1>"
            options.bottom = "<i>Copyright &#169; 2011-2026 ITOCHU Techno-Solutions Corporation.</i>"
            options.destinationDirectory = layout.buildDirectory.dir("docs/javadoc/${subproject.name}/${subproject.version}/api").get().asFile
        }
    }

    java {
        withSourcesJar()
        withJavadocJar()
    }

    afterEvaluate {
        publishing {
            publications {
                mavenJava(MavenPublication) {
                    from components.java
                    pom {
                        name = project.description
                        description = project.description
                        inceptionYear = '2014'
                        url = 'https://github.com/ctc-g/sinavi-jfw'
                        organization {
                            name = 'ITOCHU Techno-Solutions Corporation.'
                            url = 'https://www.ctc-g.co.jp'
                        }
                        licenses {
                            license {
                                name = 'The Apache Software License, Version 2.0'
                                url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                                distribution = 'repo'
                            }
                        }
                        scm {
                            connection = 'scm:git:git://github.com/ctc-g/sinavi-jfw'
                            developerConnection = 'scm:git:git://github.com/ctc-g/sinavi-jfw'
                            url = 'https://github.com/ctc-g/sinavi-jfw'
                        }
                        developers {
                            developer {
                                id = 'sinavi-jfw'
                                name = 'SINAVI J-Framework'
                                email = 'sinavi-jframework@ctc-g.co.jp'
                            }
                        }
                    }
                }
            }
            repositories {
                maven {
                    def releasesRepoUrl = 'https://oss.sonatype.org/service/local/staging/deploy/maven2'
                    def snapshotsRepoUrl = 'https://oss.sonatype.org/content/repositories/snapshots/'
                    url = version.toString().endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
                    credentials {
                        username = findProperty('sonatypeUsername') ?: ''
                        password = findProperty('sonatypePassword') ?: ''
                    }
                }
            }
        }

        signing {
            required {
                gradle.taskGraph.hasTask("publish")
            }
            sign publishing.publications.mavenJava
        }
    }

    tasks.register('codeChecks') {
        dependsOn 'checkstyleMain', 'spotbugsMain'
    }

    tasks.register('packages') {
        dependsOn 'codeChecks', 'jar', 'sourcesJar', 'javadocJar'
    }
}

project("jfw-util-core") {
    description = 'SINAVI J-Framework Utility'
    dependencies {
        implementation "commons-collections:commons-collections:${commonsCollectionsVersion}"
        implementation "org.springframework:spring-beans:${springVersion}"
    }
}

project("jfw-resource-core") {
    description = 'SINAVI J-Framework Resource'
    dependencies {
        api project(':jfw-util-core')
        implementation "commons-collections:commons-collections:${commonsCollectionsVersion}"
        api "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
    }
}

project("jfw-exception-core") {
    description = 'SINAVI J-Framework Exception'
    dependencies {
        api project(':jfw-util-core')
        api project(':jfw-resource-core')
        implementation "commons-collections:commons-collections:${commonsCollectionsVersion}"
        api "org.springframework:spring-core:${springVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
    }
}

project("jfw-web-util-core") {
    description = 'SINAVI J-Framework Web Utility'
    dependencies {
        api project(':jfw-util-core')
        api project(':jfw-exception-core')
        implementation "commons-collections:commons-collections:${commonsCollectionsVersion}"
        api "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
    }
}

project("jfw-test") {
    description = 'SINAVI J-Framework Test Utility'
    dependencies {
        api project(':jfw-util-core')
        api "commons-io:commons-io:${commonsIoVersion}"
        api "commons-fileupload:commons-fileupload:${commonsFileuploadVersion}"
        api "junit:junit:${junitVersion}"
        api "org.mockito:mockito-core:${mockitoVersion}"
        api "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}",
                "org.springframework:spring-beans:${springVersion}",
                "org.springframework:spring-test:${springVersion}"
    }
}

project("jfw-data-mongodb-test") {
    description = 'SINAVI J-Framework MongoDB Test Utility'
    dependencies {
        api project(':jfw-test')
        api "commons-io:commons-io:${commonsIoVersion}"
        api "commons-fileupload:commons-fileupload:${commonsFileuploadVersion}"
        api "junit:junit:${junitVersion}"
        api "org.mockito:mockito-core:${mockitoVersion}"
        api "org.springframework.data:spring-data-mongodb:${springMongoVersion}"
        implementation "org.codehaus.jackson:jackson-core-asl:${jacksonVersion}",
                "org.codehaus.jackson:jackson-mapper-asl:${jacksonVersion}",
                "org.codehaus.jackson:jackson-xc:${jacksonVersion}",
                "org.codehaus.jackson:jackson-jaxrs:${jacksonVersion}"
    }
}

project("jfw-web-core") {
    description = 'SINAVI J-Framework Web'
    dependencies {
        api project(':jfw-exception-core')
        api project(':jfw-web-util-core')
        implementation "javax.validation:validation-api:${beanValidationVersion}"
        implementation "commons-dbcp:commons-dbcp:${commonsDbcpVersion}"
        implementation "commons-fileupload:commons-fileupload:${commonsFileuploadVersion}"
        implementation "commons-io:commons-io:${commonsIoVersion}"
        implementation "commons-collections:commons-collections:${commonsCollectionsVersion}"
        implementation "commons-codec:commons-codec:${commonsCodecVersion}"
        implementation "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}",
                "org.springframework:spring-beans:${springVersion}",
                "org.springframework:spring-expression:${springVersion}",
                "org.springframework:spring-aop:${springVersion}",
                "org.springframework:spring-web:${springVersion}",
                "org.springframework:spring-webmvc:${springVersion}"
        implementation "org.aspectj:aspectjweaver:${aspectjVersion}"
        implementation "commons-validator:commons-validator:${commonsValidatorVersion}"
        testImplementation project(':jfw-test')
        testImplementation "javax.el:javax.el-api:${elVersion}"
        compileOnly "javax.servlet.jsp:jsp-api:${jspApiVersion}"
        compileOnly "javax.servlet:jstl:${jstlVersion}"
    }
}

project("jfw-mybatis-core") {
    description = 'SINAVI J-Framework MyBatis'
    dependencies {
        api project(':jfw-web-util-core')
        implementation "org.mybatis:mybatis:${mybatisVersion}"
        implementation "org.mybatis:mybatis-spring:${mybatisSpringVersion}"
        implementation "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}",
                "org.springframework:spring-beans:${springVersion}"
        testImplementation project(':jfw-test')
        testImplementation "org.springframework:spring-test:${springVersion}"
        testImplementation "org.springframework:spring-jdbc:${springVersion}"
        testImplementation "commons-dbcp:commons-dbcp:${commonsDbcpVersion}"
        testImplementation "com.h2database:h2:${h2Version}"
    }
}

project("jfw-rest-core") {
    description = 'SINAVI J-Framework REST Client for JAX-RS'
    dependencies {
        implementation "javax.ws.rs:javax.ws.rs-api:${jaxRsVersion}"
        implementation "org.codehaus.jackson:jackson-core-asl:${jacksonVersion}",
                "org.codehaus.jackson:jackson-mapper-asl:${jacksonVersion}"
    }
}

project("jfw-rest-plugin-jersey") {
    description = 'SINAVI J-Framework REST Client for JAX-RS (Jersey)'
    dependencies {
        api project(':jfw-util-core')
        api project(':jfw-exception-core')
        api project(':jfw-rest-core')
        implementation "org.glassfish.jersey.containers:jersey-container-servlet:${jerseyVersion}",
                "org.glassfish.jersey.core:jersey-client:${jerseyVersion}",
                "org.glassfish.jersey.connectors:jersey-grizzly-connector:${jerseyVersion}",
                "org.glassfish.jersey.connectors:jersey-apache-connector:${jerseyVersion}",
                "org.glassfish.jersey.ext:jersey-bean-validation:${jerseyVersion}",
                "org.glassfish.jersey.media:jersey-media-json-jackson:${jerseyVersion}"
        testImplementation "org.glassfish.jersey.test-framework:jersey-test-framework-core:${jerseyVersion}",
                "org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-simple:${jerseyVersion}",
                "org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-external:${jerseyVersion}",
                "org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-default-client:${jerseyVersion}"
        testImplementation project(':jfw-validation-core')
    }
}

project("jfw-rest-plugin-springmvc") {
    description = 'SINAVI J-Framework REST Plugin for SpringMVC'
    dependencies {
        api project(':jfw-rest-core')
        api project(':jfw-exception-core')
        implementation "org.springframework:spring-context:${springVersion}",
                "org.springframework:spring-web:${springVersion}",
                "org.springframework:spring-webmvc:${springVersion}"
        implementation 'org.apache.httpcomponents:httpclient:4.3'
        testImplementation "org.springframework:spring-test:${springVersion}"
        testImplementation("org.eclipse.jetty:jetty-servlet:8.1.5.v20120716") {
            exclude group: "org.eclipse.jetty.orbit", module: "javax.servlet"
        }
        testImplementation("org.eclipse.jetty:jetty-server:8.1.5.v20120716") {
            exclude group: "org.eclipse.jetty.orbit", module: "javax.servlet"
        }
    }
}

project("jfw-validation-core") {
    description = 'SINAVI J-Framework Bean Validation'
    dependencies {
        api(project(':jfw-util-core'))
        api "javax.validation:validation-api:${beanValidationVersion}"
        api "org.hibernate:hibernate-validator:${hibernateValidatorVersion}"
        implementation "javax.el:javax.el-api:${elVersion}"
        implementation "org.glassfish.web:javax.el:${elVersion}"
        implementation "commons-validator:commons-validator:${commonsValidatorVersion}"
    }
}

project("jfw-amqp-core") {
    description = 'SINAVI J-Framework AMQP'
    dependencies {
        api project(':jfw-util-core')
        api project(':jfw-exception-core')
        implementation "org.springframework.amqp:spring-amqp:${springAmqpVersion}",
                "org.springframework.amqp:spring-rabbit:${springAmqpVersion}"
        implementation "org.springframework.retry:spring-retry:${springRetryVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
        testImplementation "org.springframework:spring-tx:${springVersion}"
        runtimeOnly "org.codehaus.jackson:jackson-core-asl:${jacksonVersion}",
                "org.codehaus.jackson:jackson-mapper-asl:${jacksonVersion}"
    }
}

project("jfw-csv-core") {
    description = 'SINAVI J-Framework CSV'
    dependencies {
        api project(':jfw-util-core')
        api project(':jfw-exception-core')
        api project(':jfw-validation-core')
        implementation "net.sf.opencsv:opencsv:${openCsvVersion}"
        implementation 'net.sourceforge.collections:collections-generic:4.01'
        implementation "org.mybatis:mybatis:${mybatisVersion}"
        testImplementation project(':jfw-test')
        testImplementation "org.mybatis:mybatis-spring:${mybatisSpringVersion}"
        testImplementation "org.springframework:spring-jdbc:${springVersion}"
        testImplementation "com.h2database:h2:${h2Version}"
    }
}

project("jfw-excel-core") {
    description = 'SINAVI J-Framework Excel'
    dependencies {
        implementation 'jp.sf.amateras.xlsbeans:xlsbeans:1.2.1'
    }
}
