plugins {
    id 'java'
    id 'com.github.hierynomus.license' version '0.16.1' apply false
    id 'com.github.spotbugs' version '6.0.18' apply false
    id 'maven-publish'
    id 'signing'
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'checkstyle'
    apply plugin: 'com.github.spotbugs'
    apply plugin: 'jacoco'
    apply plugin: 'idea'
    apply plugin: 'com.github.hierynomus.license'
    apply plugin: 'signing'
    apply plugin: 'maven-publish'
    apply plugin: 'project-report'

    repositories {
        mavenCentral()
        maven {
            url 'https://repo.spring.io/milestone'
        }
        maven {
            url 'https://repo.spring.io/snapshot'
        }
    }

    eclipse {
        classpath {
            downloadSources = true
        }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    [javadoc]*.options*.encoding = 'UTF-8'
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    license {
        ext.year = Calendar.getInstance().get(Calendar.YEAR)
        header rootProject.file("${rootDir}/config/LICENSE_TEMPLATE")
        ignoreFailures false
        skipExistingHeaders true
        strictCheck true
        useDefaultMappings false
        mapping('java', "SLASHSTAR_STYLE")
    }

    compileJava.dependsOn("licenseTest")
    compileTestJava.dependsOn("licenseTest")

    configurations {
        compileOnly
        implementation.extendsFrom compileOnly
        all*.exclude group: "commons-logging", module: "commons-logging"
    }

    ext {
        springVersion = '6.1.14'
        springDataMongoVersion = '4.2.12'
        springAmqpVersion = '3.1.7'
        springRetryVersion = '2.0.9'
        jakartaRsVersion = '3.1.0'
        jacksonVersion = '2.17.2'
        jerseyVersion = '3.1.7'
        mybatisVersion = '3.5.16'
        mybatisSpringVersion = '3.0.3'
        beanValidationVersion = '3.0.2'
        hibernateValidatorVersion = '8.0.1.Final'
        elVersion = '5.0.1'
        commonsFileuploadVersion = '1.5'
        commonsValidatorVersion = '1.9.0'
        commonsDbcp2Version = '2.12.0'
        commonsIoVersion = '2.16.1'
        commonsCollections4Version = '4.4'
        commonsLang3Version = '3.14.0'
        commonsCodecVersion = '1.17.0'
        slf4jVersion = '2.0.13'
        logbackVersion = '1.5.6'
        guavaVersion = '33.2.1-jre'
        openCsvVersion = '5.9'
        poiVersion = '5.2.5'

        junitVersion = '5.10.3'
        mockitoVersion = '5.12.0'
        h2Version = '2.2.224'

        servletApiVersion = '6.0.0'
        aspectjVersion = '1.9.22.1'
        jspApiVersion = '3.1.1'
        jstlVersion = '3.0.1'

        checkstyleVersion = '10.17.0'
    }

    dependencies {
        implementation "org.slf4j:slf4j-api:${slf4jVersion}"
        implementation "ch.qos.logback:logback-classic:${logbackVersion}"
        implementation "org.slf4j:jcl-over-slf4j:${slf4jVersion}"
        implementation "com.google.guava:guava:${guavaVersion}"
        implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"
        testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
        testImplementation "junit:junit:4.13.2"
        testImplementation "org.junit.vintage:junit-vintage-engine:${junitVersion}"
        testImplementation "org.hamcrest:hamcrest:2.2"
        testImplementation "org.mockito:mockito-core:${mockitoVersion}"
        testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
        checkstyle "com.puppycrawl.tools:checkstyle:${checkstyleVersion}"
        runtimeOnly "org.aspectj:aspectjweaver:${aspectjVersion}"
        compileOnly "jakarta.servlet:jakarta.servlet-api:${servletApiVersion}"
    }

    test {
        useJUnitPlatform()
        testLogging {
            events "failed"
            exceptionFormat "full"
            debug {
                events "started", "skipped", "failed"
                exceptionFormat "full"
            }
        }
        exclude '**/*$*'
    }

    checkstyle {
        configFile = file("${rootDir}/config/checkstyle/ctc-checks.xml")
        ignoreFailures = true
        toolVersion = "${checkstyleVersion}"
    }

    spotbugs {
        ignoreFailures = true
        excludeFilter = file("${rootDir}/config/spotbugs/exclude.xml")
    }

    jacoco {
        toolVersion = '0.8.12'
    }

    jacocoTestReport {
        reports {
            xml.required = false
            csv.required = false
            html.outputLocation = layout.buildDirectory.dir("jacocoHtml")
        }
    }

    sourceSets {
        test {
            resources {
                srcDirs += sourceSets.main.resources.srcDirs
            }
        }
    }
}

wrapper {
    gradleVersion = "8.8"
}

configure(subprojects) { subproject ->
    group = 'jp.co.ctc-g.jfw'
    defaultTasks 'clean', 'packages'
    jar {
        doFirst {
            manifest.attributes["Created-By"] = "${System.getProperty("java.version")}"
            manifest.attributes["Implementation-Vendor"] = 'ITOCHU Techno-Solutions Corporation.'
            manifest.attributes["Implementation-Title"] = subproject.name
            manifest.attributes["Implementation-Version"] = subproject.version
        }
    }
    javadoc {
        doFirst {
            description = "Generates project-level javadoc for use in -javadoc jar"
            options.memberLevel = org.gradle.external.javadoc.JavadocMemberLevel.PROTECTED
            options.author = true
            options.overview = "${rootDir}/config/javadoc/html/overview.html"
            options.charSet = 'UTF-8'
            options.docTitle = "${subproject.name} ${subproject.version}"
            options.windowTitle = "${subproject.name} ${subproject.version}"
            options.header = "<h1>${subproject.name}</h1>"
            options.bottom = "<i>Copyright &#169; 2011-2014 ITOCHU Techno-Solutions Corporation.</i>"
            options.destinationDirectory = file("${project.layout.buildDirectory.get()}/docs/javadoc/${subproject.name}/${subproject.version}/api")
        }
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
                groupId = 'jp.co.ctc-g.jfw'
                pom {
                    packaging = 'jar'
                    inceptionYear = '2014'
                    url = 'https://github.com/ctc-g/sinavi-jfw'
                    organization {
                        name = 'ITOCHU Techno-Solutions Corporation.'
                        url = 'https://www.ctc-g.co.jp'
                    }
                    licenses {
                        license {
                            name = 'The Apache Software License, Version 2.0'
                            url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                            distribution = 'repo'
                        }
                    }
                    scm {
                        connection = 'scm:git:git://github.com/ctc-g/sinavi-jfw'
                        developerConnection = 'scm:git:git://github.com/ctc-g/sinavi-jfw'
                        url = 'https://github.com/ctc-g/sinavi-jfw'
                    }
                    developers {
                        developer {
                            id = 'sinavi-jfw'
                            name = 'SINAVI J-Framework'
                            email = 'sinavi-jframework@ctc-g.co.jp'
                        }
                    }
                }
            }
        }
        repositories {
            maven {
                def releasesRepoUrl = 'https://oss.sonatype.org/service/local/staging/deploy/maven2'
                def snapshotsRepoUrl = 'https://oss.sonatype.org/content/repositories/snapshots/'
                url = version.toString().endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
                credentials {
                    username = findProperty('sonatypeUsername') ?: ''
                    password = findProperty('sonatypePassword') ?: ''
                }
            }
        }
    }

    signing {
        required { gradle.taskGraph.hasTask("publish") }
        sign publishing.publications.mavenJava
    }

    java {
        withSourcesJar()
        withJavadocJar()
    }

    tasks.register('codeChecks') {
        dependsOn 'checkstyleMain', 'spotbugsMain'
    }
    tasks.register('packages') {
        dependsOn 'codeChecks', 'jar', 'sourcesJar', 'javadocJar'
    }
}

project("jfw-util-core") {
    description = 'SINAVI J-Framework Utility'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation "org.apache.commons:commons-collections4:${commonsCollections4Version}"
        implementation "org.springframework:spring-beans:${springVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-resource-core") {
    description = 'SINAVI J-Framework Resource'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation "org.apache.commons:commons-collections4:${commonsCollections4Version}"
        implementation "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-exception-core") {
    description = 'SINAVI J-Framework Exception'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation project(':jfw-resource-core')
        implementation "org.apache.commons:commons-collections4:${commonsCollections4Version}"
        implementation "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-web-util-core") {
    description = 'SINAVI J-Framework Web Utility'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation project(':jfw-exception-core')
        implementation "org.apache.commons:commons-collections4:${commonsCollections4Version}"
        implementation "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-test") {
    description = 'SINAVI J-Framework Test Utility'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation "commons-io:commons-io:${commonsIoVersion}"
        implementation "commons-fileupload:commons-fileupload:${commonsFileuploadVersion}"
        implementation "junit:junit:4.13.2"
        implementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
        implementation "org.mockito:mockito-core:${mockitoVersion}"
        implementation "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}",
                "org.springframework:spring-beans:${springVersion}",
                "org.springframework:spring-test:${springVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-data-mongodb-test") {
    description = 'SINAVI J-Framework MongoDB Test Utility'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-test')
        implementation project(':jfw-util-core')
        implementation "commons-io:commons-io:${commonsIoVersion}"
        implementation "commons-fileupload:commons-fileupload:${commonsFileuploadVersion}"
        implementation "junit:junit:4.13.2"
        implementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
        implementation "org.mockito:mockito-core:${mockitoVersion}"
        implementation "org.springframework:spring-test:${springVersion}",
                "org.springframework:spring-context:${springVersion}"
        implementation "org.springframework.data:spring-data-mongodb:${springDataMongoVersion}"
        implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}",
                "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}",
                "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-web-core") {
    description = 'SINAVI J-Framework Web'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation project(':jfw-resource-core')
        implementation project(':jfw-exception-core')
        implementation project(':jfw-web-util-core')
        implementation "org.aspectj:aspectjrt:${aspectjVersion}"
        implementation "jakarta.validation:jakarta.validation-api:${beanValidationVersion}"
        implementation "org.apache.commons:commons-dbcp2:${commonsDbcp2Version}"
        implementation "commons-fileupload:commons-fileupload:${commonsFileuploadVersion}"
        implementation "commons-io:commons-io:${commonsIoVersion}"
        implementation "org.apache.commons:commons-collections4:${commonsCollections4Version}"
        implementation "commons-codec:commons-codec:${commonsCodecVersion}"
        implementation "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}",
                "org.springframework:spring-beans:${springVersion}",
                "org.springframework:spring-expression:${springVersion}",
                "org.springframework:spring-aop:${springVersion}",
                "org.springframework:spring-web:${springVersion}",
                "org.springframework:spring-webmvc:${springVersion}"
        implementation "commons-validator:commons-validator:${commonsValidatorVersion}"
        testImplementation project(':jfw-test')
        testImplementation "jakarta.el:jakarta.el-api:${elVersion}"
        compileOnly "jakarta.servlet.jsp:jakarta.servlet.jsp-api:${jspApiVersion}"
        compileOnly "jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:${jstlVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-mybatis-core") {
    description = 'SINAVI J-Framework MyBatis'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation project(':jfw-web-util-core')
        implementation "org.mybatis:mybatis:${mybatisVersion}"
        implementation "org.mybatis:mybatis-spring:${mybatisSpringVersion}"
        implementation "org.springframework:spring-core:${springVersion}",
                "org.springframework:spring-context:${springVersion}",
                "org.springframework:spring-beans:${springVersion}"
        testImplementation project(':jfw-test')
        testImplementation "org.springframework:spring-test:${springVersion}"
        testImplementation "org.springframework:spring-jdbc:${springVersion}"
        testImplementation "org.apache.commons:commons-dbcp2:${commonsDbcp2Version}"
        testImplementation "com.h2database:h2:${h2Version}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-rest-core") {
    description = 'SINAVI J-Framework REST Client for JAX-RS'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation "jakarta.ws.rs:jakarta.ws.rs-api:${jakartaRsVersion}"
        implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}",
                "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}",
                "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-rest-plugin-jersey") {
    description = 'SINAVI J-Framework REST Client for JAX-RS (Jersey)'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation project(':jfw-exception-core')
        implementation project(':jfw-rest-core')
        implementation "org.glassfish.jersey.containers:jersey-container-servlet:${jerseyVersion}",
                "org.glassfish.jersey.core:jersey-client:${jerseyVersion}",
                "org.glassfish.jersey.connectors:jersey-grizzly-connector:${jerseyVersion}",
                "org.glassfish.jersey.connectors:jersey-apache-connector:${jerseyVersion}",
                "org.glassfish.jersey.ext:jersey-bean-validation:${jerseyVersion}",
                "org.glassfish.jersey.media:jersey-media-json-jackson:${jerseyVersion}",
                "org.glassfish.jersey.inject:jersey-hk2:${jerseyVersion}"
        testImplementation "org.glassfish.jersey.test-framework:jersey-test-framework-core:${jerseyVersion}",
                "org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-simple:${jerseyVersion}",
                "org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-external:${jerseyVersion}"
        testImplementation project(':jfw-validation-core')
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-rest-plugin-springmvc") {
    description = 'SINAVI J-Framework REST Plugin for SpringMVC'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation project(':jfw-rest-core')
        implementation project(':jfw-exception-core')
        implementation "org.springframework:spring-context:${springVersion}",
                "org.springframework:spring-test:${springVersion}",
                "org.springframework:spring-web:${springVersion}",
                "org.springframework:spring-webmvc:${springVersion}"
        implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'
        testImplementation "org.springframework:spring-test:${springVersion}"
        testImplementation "org.eclipse.jetty:jetty-servlet:11.0.21"
        testImplementation "org.eclipse.jetty:jetty-server:11.0.21"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-validation-core") {
    description = 'SINAVI J-Framework Bean Validation'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation(project(':jfw-util-core'))
        implementation "jakarta.validation:jakarta.validation-api:${beanValidationVersion}"
        implementation "org.hibernate.validator:hibernate-validator:${hibernateValidatorVersion}"
        implementation "jakarta.el:jakarta.el-api:${elVersion}"
        implementation "org.glassfish.expressly:expressly:5.0.0"
        implementation "commons-validator:commons-validator:${commonsValidatorVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-amqp-core") {
    description = 'SINAVI J-Framework AMQP'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation project(':jfw-exception-core')
        implementation "org.springframework.amqp:spring-amqp:${springAmqpVersion}",
                "org.springframework.amqp:spring-rabbit:${springAmqpVersion}"
        implementation "org.springframework.retry:spring-retry:${springRetryVersion}"
        testImplementation "org.springframework:spring-test:${springVersion}"
        testImplementation "org.springframework:spring-tx:${springVersion}"
        runtimeOnly "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}",
                "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-csv-core") {
    description = 'SINAVI J-Framework CSV'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation project(':jfw-util-core')
        implementation project(':jfw-exception-core')
        implementation project(':jfw-validation-core')
        implementation "jakarta.validation:jakarta.validation-api:${beanValidationVersion}"
        implementation "com.opencsv:opencsv:${openCsvVersion}"
        implementation "org.mybatis:mybatis:${mybatisVersion}"
        testImplementation project(':jfw-test')
        testImplementation "commons-io:commons-io:${commonsIoVersion}"
        testImplementation "org.mybatis:mybatis-spring:${mybatisSpringVersion}"
        testImplementation "org.springframework:spring-jdbc:${springVersion}"
        testImplementation "com.h2database:h2:${h2Version}"
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}

project("jfw-excel-core") {
    description = 'SINAVI J-Framework Excel'
    defaultTasks 'clean', 'packages'
    dependencies {
        implementation "org.apache.poi:poi:${poiVersion}"
        implementation "org.apache.poi:poi-ooxml:${poiVersion}"
    }
    sourceSets {
        test {
            java {
                exclude '**/*'
            }
        }
    }
    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    name = project.description
                    description = project.description
                }
            }
        }
    }
}
